services:
  - type: web
    name: shop-app
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shop-db
          property: connectionString

databases:
  - name: shop-db
    plan: free
    databaseName: shop
    user: shop_user
